POST http://localhost:3333/books
Content-Type: application/json

{
    "title": "Estrelas bonitas",
    "details": "as estrelas sao lindas"
}

###
GET http://localhost:3333/books

###
GET http://localhost:3333/books/25dfa450-0f06-4042-8d64-69a43e73ccce

####

PATCH http://localhost:3333/books/25dfa450-0f06-4042-8d64-69a43e73ccce
Content-Type: application/json

{
    "title": "Percy Jackson: the lightning thief",
    "details": ""
}